apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
  namespace: mock-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
      - name: backend-service
        image: nguyenbavu1902/backend-service:v0.0.1
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: backend-config