apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mock-project
spec:
  selector:
    app: backend-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP