apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-service
  namespace: mock-project
  labels:
    app: database-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database-service
  template:
    metadata:
      labels:
        app: database-service
    spec:
      containers:
        - name: database-service
          image: nguyenbavu1902/database-service:v0.0.1
          ports:
            - containerPort: 8081
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_PASSWORD
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: MONGO_PORT
            - name: MONGO_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: MONGO_DBNAME
            - name: MONGO_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: MONGO_OPTIONS

            - name: MONGO_URI
              value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@$(MONGO_HOST):$(MONGO_PORT)/$(MONGO_DBNAME)$(MONGO_OPTIONS)"