apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: mock-project
spec:
  selector:
    app: database-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
